Backport compliance check from dav1d 1.4.0
memorysafety/rav1d pull request #1071
Opened 2024-05-13 18:29 UTC by fbossen

Check for trailing marker/zero bits in tile data

2024-05-14 02:13 UTC, kkysen requested changes

2024-05-14 02:18 UTC, fbossen commented on src/msac.rs
> +    }
Note that `offset` is generally negative here. The slice returned by `buf()` isn't large enough.

2024-06-26 06:34 UTC, rinon commented on src/msac.rs
> +    }
@kkysen what is the status here? looks like you abandoned #1074, can we just use this then?

2024-06-27 06:01 UTC, kkysen commented on src/msac.rs
> +    }
Sorry, didn't abandon that one. Just kept forgetting to fix it up.  I'll do that now.

2024-06-28 08:44 UTC, kkysen commented on src/msac.rs
> +    }
You can fix this PR now based on #1074, I think.  You should be able to use `.data()` and `.buf_index()` with `.wrapping_add_signed` and it'll all be safe code.

2024-07-09 19:19 UTC, kkysen approved these changes

2024-07-09 21:06 UTC, merged