`ipred_z*_neon`: Cleanup and make safer
memorysafety/rav1d pull request #1184
Opened 2024-06-08 00:36 UTC by randomPoison

Part of https://github.com/memorysafety/rav1d/issues/846 and https://github.com/memorysafety/rav1d/issues/815

2024-06-09 04:02 UTC, kkysen requested changes
Can you also move the `.as_ptr()`/`.as_mut_ptr()`-type calls to the `fn call`s instead of repeating them at the call sites?

2024-06-09 04:02 UTC, kkysen commented on src/ipred.rs
>                      flipped.as_mut_ptr().offset(1),
```suggestion
                    flipped[1..].as_mut_ptr(),
```

2024-06-09 04:02 UTC, kkysen commented on src/ipred.rs
> +        // SAFETY: Reconstructed from args passed by `angular_ipred::Fn::call`.
Can you also add the `# Safety` comment on `fn ipred_z_neon_erased` saying it must be called by ``[`angular_ipred::Fn::call`]``?

2024-06-10 19:49 UTC, kkysen requested changes
Other new changes look good, but you can do this, too? https://github.com/memorysafety/rav1d/pull/1184#pullrequestreview-2106061876

2024-06-10 19:49 UTC, kkysen commented on src/ipred.rs
> +    /// SAFETY: Must be called from [`angular_ipred::Fn::call`].
```suggestion
    /// # Safety
    ///
    /// Must be called from [`angular_ipred::Fn::call`].
```

`# Safety` is used for docs, vs. `// SAFETY` for comments for `unsafe {}` blocks.

2024-06-10 22:37 UTC, randomPoison commented
> Can you also move the `.as_ptr()`/`.as_mut_ptr()`-type calls to the `fn call`s instead of repeating them at the call sites?

I'm not sure what you're asking for here. Are you referring to the places in the `ipred_z*_neon` fns where we pass a pointer to a buffer into the asm routines? So e.g. instead of:

```rust
let buf = [0; N];
some_asm_call(buf.as_ptr());
another_asm_call(buf.as_ptr());
```

we'd do:

```rust
let buf = [0; N];
let buf_ptr = buf.as_ptr();
some_asm_call(buf_ptr);
another_asm_call(buf_ptr);
```

Is that what you had in mind? That doesn't really seem any cleaner to me, it seems better to convert to a pointer at the call site. Am I misunderstanding what you're suggesting?

2024-06-12 16:21 UTC, kkysen commented
> > Can you also move the `.as_ptr()`/`.as_mut_ptr()`-type calls to the `fn call`s instead of repeating them at the call sites?
> 
> I'm not sure what you're asking for here. Are you referring to the places in the `ipred_z*_neon` fns where we pass a pointer to a buffer into the asm routines? So e.g. instead of:
> 
> ```rust
> let buf = [0; N];
> some_asm_call(buf.as_ptr());
> another_asm_call(buf.as_ptr());
> ```
> 
> we'd do:
> 
> ```rust
> let buf = [0; N];
> let buf_ptr = buf.as_ptr();
> some_asm_call(buf_ptr);
> another_asm_call(buf_ptr);
> ```
> 
> Is that what you had in mind? That doesn't really seem any cleaner to me, it seems better to convert to a pointer at the call site. Am I misunderstanding what you're suggesting?

No, I meant, we're doing things like `.call::<BD>(buf[..n].as_ptr())` repeatedly instead of doing `.call::<BD(&buf[..n])` and doing the `let buf = buf.as_ptr()` inside of the `fn call`.  The approach we've been doing for most of the `fn call`s wrapping `fn` ptrs.

2024-06-12 21:11 UTC, randomPoison commented
Ah, okay that makes sense. I've made that change.

2024-06-13 20:40 UTC, kkysen requested changes
One little thing left: for the places where you did `let (front, back) = _.split_at_mut(...);`, can you name them `in`, `out` or `src`, `dst` instead, for clarity, and matching the arg names and var names used elsewhere?

2024-06-13 20:40 UTC, kkysen commented on src/ipred.rs
> +                let (front, back) = buf.split_at_mut(1 + left_offset);
Maybe `out` and `in_0` are better names, corresponding to the arg names.

2024-06-13 20:40 UTC, kkysen commented on src/ipred.rs
> +            let (front, back) = buf.split_at_mut(left_offset);
Same here.

2024-06-13 21:41 UTC, randomPoison commented
Done, I went with `src` and `dst`.

2024-06-13 21:45 UTC, kkysen approved these changes

2024-06-13 23:28 UTC, merged