`struct ITUTT35PayloadPtr`: Newtype `Dav1dITUTT35::payload` to `unsafe impl Send + Sync` on it
memorysafety/rav1d pull request #1277
Opened 2024-07-01 18:00 UTC by kkysen

2024-07-01 23:12 UTC, randomPoison approved these changes

2024-07-02 20:29 UTC, rinon commented
Why do we need Send and Sync for a C interface type? I don't think we should impl anything on this type, we should implement it for the container that contains one of these.

2024-07-02 20:30 UTC, rinon requested changes
It looks like this is used in a `DRav1d`? Maybe we should impl Send and Sync if the safe rav1d side of the `DRav1d` impls them.

2024-07-03 07:31 UTC, kkysen commented
> It looks like this is used in a `DRav1d`? Maybe we should impl Send and Sync if the safe rav1d side of the `DRav1d` impls them.

It'd be unsound to do this since there are not sufficient constraints on the generics in `DRav1d<R, D>` to guarantee such an `unsafe impl` would be sound.

2024-07-03 18:06 UTC, rinon commented
How so exactly? We should never access and use the C type from Rust, right? So we can't enforce anything about it. I'm basically thinking of the `D` part of that structure as opaque from Rust's perspective, is that not the case?

2024-07-11 21:34 UTC, kkysen commented
> How so exactly? We should never access and use the C type from Rust, right? So we can't enforce anything about it. I'm basically thinking of the `D` part of that structure as opaque from Rust's perspective, is that not the case?

The whole type is public, so C callers can do whatever they want with the `D` type.  I think it makes sense to limit the safety constraints on it to one particular type rather than a blanket impl that can hide a ton of stuff on the many other types that don't need it.

2024-07-11 21:54 UTC, merged