`struct StableRef`: Refactor out from `CArc::{,base_}stable_ref` and `unsafe impl Send + Sync` on it
memorysafety/rav1d pull request #1278
Opened 2024-07-01 18:44 UTC by kkysen

* Part of #1177.

This helps make `CArc<T: Send + Sync>: Send + Sync` (still need to fix `CBox` in the next PR).

2024-07-01 23:14 UTC, randomPoison approved these changes

2024-07-02 20:32 UTC, rinon requested changes
Why can't you just impl `Send+Sync` for `CArc` if `T` implements them?

2024-07-02 20:46 UTC, kkysen commented on src/c_arc.rs
>          // [`Self::stable_Ref`] is always updated on writes to [`Self::owner`],
```suggestion
        // [`Self::stable_ref`] is always updated on writes to [`Self::owner`],
```

2024-07-02 22:38 UTC, rinon reviewed
We talked offline about this, it's ok, just a few small doc comments now.

2024-07-02 22:38 UTC, rinon commented on src/c_arc.rs
> +/// It is stable (e.x. from a [`Box`] or a [`CBox`]),
Shouldn't this be a `Pin<Box<T>`? We don't want the object to move out of its allocation.

Can we put a SAFETY comment here that any pointer stored here MUST not move for its lifetime?

2024-07-02 22:38 UTC, rinon commented on src/c_arc.rs
> +/// SAFETY: [`StableRef`]`<T>` is essentially `&T`, which is [`Send`] if `T: `[`Send`]`.
This is only valid if the invariants on what is put into the ref is held, we should at least mention that here.

2024-07-03 06:14 UTC, merged