`src/cdef`: Deduplicate w/ generics
memorysafety/rav1d pull request #591
Opened 2023-11-27 12:21 UTC by thedataking

Also adds ToPrimitive<i16> for BitDepth::Pixel.

2023-12-05 16:55 UTC, kkysen reviewed
By the way, how did you get git to treat the deduplicated file as a moved and edited version of the `_tmpl_16.rs` file?  It's much easier to review that way and spot differences that could be causing the arm CI failures.

2023-12-05 17:01 UTC, kkysen requested changes
The `fn *_neon_erased`s aren't bitdepth generic and aren't dispatching to the correct bitdepth `fn`s (just one of them).

2023-12-05 17:01 UTC, kkysen commented on src/cdef.rs
> +    dav1d_cdef_filter8_8bpc_neon(
You're calling the bitdepth-specific versions here; this `fn` needs to be generic and dispatch on `BD::BPC`.

2023-12-06 10:46 UTC, thedataking commented
> By the way, how did you get git to treat the deduplicated file as a moved and edited version of the _tmpl_16.rs file?

No idea. I just used `git rm ...` 🤷‍♂️  

> The fn *_neon_eraseds aren't bitdepth generic and aren't dispatching to the correct bitdepth fns (just one of them).

yeah, should have waited for the CI to finish before pinging you; thanks!

2024-01-10 22:31 UTC, kkysen requested changes
Just a couple of little changes left.

2024-01-10 22:31 UTC, kkysen commented on src/cdef.rs
> +
```suggestion
```

2024-01-10 22:31 UTC, kkysen commented on src/cdef.rs
> +        let bitdepth_min_8 = 32 - clz(bd.bitdepth_max().as_::<c_uint>()) - 8;
```suggestion
        let bitdepth_min_8 = bd.bitdepth().as_::<c_int>() - 8;
```

2024-01-10 22:31 UTC, kkysen commented on src/cdef.rs
> +    let bitdepth_min_8 = 32 - clz(bd.bitdepth_max().as_::<c_uint>()) - 8;
```suggestion
    let bitdepth_min_8 = bd.bitdepth().as_::<c_int>() - 8;
```

2024-01-10 22:31 UTC, kkysen commented on src/cdef.rs
> +    cdef_filter_block_c::<BD>(
```suggestion
    cdef_filter_block_c(
```

2024-01-10 22:31 UTC, kkysen commented on src/cdef.rs
> +#[cfg(all(feature = "asm", any(target_arch = "arm", target_arch = "aarch64"),))]
```suggestion
#[cfg(feature = "asm")]
```

See below for the other import removed.

2024-01-10 22:31 UTC, kkysen commented on src/cdef.rs
> +
```suggestion
```

2024-01-10 22:31 UTC, kkysen commented on src/cdef.rs
> +            (*c).fb[0] = dav1d_cdef_filter_8x8_8bpc_sse2;
```suggestion
            if !flags.contains(CpuFlags::SSSE2) {
                return;
            }

            (*c).fb[0] = dav1d_cdef_filter_8x8_8bpc_sse2;
```

2024-01-10 22:31 UTC, kkysen commented on src/cdef.rs
> +            (*c).fb[0] = dav1d_cdef_filter_8x8_8bpc_sse2;
By the way, this logic is harder to review/map back to the C when the two bitdepth branches are fully separated, i.e. one `match` vs. a `match` for each `fn` ptr (like how `bd_fn!` does it).  It's fine for now, though.

2024-01-12 00:40 UTC, kkysen approved these changes

2024-01-12 00:41 UTC, merged