`mod intra_edge`: Backport memory reduction from dav1d 1.2.1
memorysafety/rav1d pull request #830
Opened 2024-03-17 17:00 UTC by fbossen

Eliminate duplicate and constant `intra_edge` table entries

2024-03-17 17:00 UTC, fbossen commented
Relates to #286

2024-03-17 18:41 UTC, folkertdev reviewed
I think this looks good except for some minor style/consistency nitpicks

2024-03-17 18:41 UTC, folkertdev commented on src/intra_edge.rs
> +    pub const EDGE_NONE: Self = Self::empty();
I think we can drop the `EDGE_` prefix from these constants. They'll always occur qualified as `EdgeFlags::*` so the edge bit is just repeated.

2024-03-17 18:41 UTC, folkertdev commented on src/intra_edge.rs
> +        );
the convention we went with here is that variables can use `union`, so `foo.union(...)`, but when the left-hand side is an enum variant we use `union_all`:

```suggestion
        let h4 = EdgeFlags::union_all([
            EdgeFlags::LEFT_HAS_BOTTOM,
            edge_flags
                .intersection(EdgeFlags::I420_TOP_HAS_RIGHT)
                .select(matches!(bl, BlockLevel::Bl16x16)),
        ]);
```

2024-03-17 18:41 UTC, folkertdev commented on src/intra_edge.rs
> +        );
like above

```suggestion
        let v4 = EdgeFlags::union_all([
            EdgeFlags::TOP_HAS_RIGHT,
            edge_flags
                .intersection(EdgeFlags::union_all([
                    EdgeFlags::I420_LEFT_HAS_BOTTOM,
                    EdgeFlags::I422_LEFT_HAS_BOTTOM,
                ]))
                .select(matches!(bl, BlockLevel::Bl16x16)),
        ]);
```

2024-03-17 19:19 UTC, fbossen commented
> I think this looks good except for some minor style/consistency nitpicks

Thanks for the feedback. I made the suggested changes.

2024-03-17 20:04 UTC, folkertdev approved these changes

2024-03-19 03:15 UTC, kkysen requested changes
Mostly looks very good, but I had a few more suggestions.  Also, by using 2-byte `EdgeIndex`s instead of 8-byte pointers, our table should be even smaller than C's 🎉 .

2024-03-19 03:15 UTC, kkysen commented on src/intra_edge.rs
> +        ]);
```suggestion
        let v4 = edge_flags
            .intersection(EdgeFlags::union_all([
                EdgeFlags::I420_LEFT_HAS_BOTTOM,
                EdgeFlags::I422_LEFT_HAS_BOTTOM,
            ]))
            .select(matches!(bl, BlockLevel::Bl16x16))
            .union(EdgeFlags::TOP_HAS_RIGHT),
```

2024-03-19 03:15 UTC, kkysen commented on src/intra_edge.rs
> +    pub const LEFT_HAS_BOTTOM: Self = Self::union_all([
```suggestion
    pub const ALL_LEFT_HAS_BOTTOM: Self = Self::union_all([
```

I should've done this when I added this, but could add this in a separate commit on this PR?

2024-03-19 03:15 UTC, kkysen commented on src/intra_edge.rs
> +    pub const TOP_HAS_RIGHT: Self = Self::union_all([
```suggestion
    pub const ALL_TOP_HAS_RIGHT: Self = Self::union_all([
```

Same reasoning and commit as above.

2024-03-19 19:57 UTC, kkysen approved these changes

2024-03-19 23:17 UTC, merged