`enum CompInterType`: make a real enum
memorysafety/rav1d pull request #869
Opened 2024-03-20 08:30 UTC by folkertdev

this PR looks big but most lines are because I needed to reverse two branches so that 

```rust
if comp_type.is_none() { ... } else { ... }
```

can turn into

```rust
if let Some(comp_type) = comp_type { ... }  else { ... }
```

the first commit is most changes, the second one just the switching of branches and using the variable bound by the if-let

2024-03-20 16:14 UTC, kkysen requested changes
Still reviewing the second commit.

2024-03-20 16:14 UTC, kkysen commented on src/levels.rs
> +}
```suggestion
pub enum CompInterType {
    WeightedAvg = 1,
    Avg = 2,
    Seg = 3,
    Wedge = 4,
}
```

2024-03-21 20:47 UTC, kkysen approved these changes
The 2nd commit is too annoying to review.  It's just the `if let Some` and swapping the branches' order, right?  If that's it, it LGTM.

2024-03-21 21:12 UTC, folkertdev commented
yes, that and it removes these lines

```rust
// TODO use if let in the surrounding if structure
let comp_inter_type = b.c2rust_unnamed.c2rust_unnamed_0.comp_type.unwrap();
```

because that variable is now bound by the `if let`

2024-03-21 21:42 UTC, merged