`enum Rav1dRestorationType`: backport optimization from dav1d 1.3.0
memorysafety/rav1d pull request #876
Opened 2024-03-20 20:17 UTC by fbossen

Embed `sgr_idx` into `enum Rav1dRestorationType` to avoid storing it separately. Define `enum Rav1dRestorationType` as `repr(u8)` to match C code and save some memory.

2024-03-20 22:20 UTC, kkysen requested changes

2024-03-20 22:20 UTC, kkysen commented on include/dav1d/headers.rs
> +#[repr(u8)]
We shouldn't need this.  It'll choose the smallest size anyways and specifying a repr disables niche optimizations I believe.

2024-03-20 22:20 UTC, kkysen commented on include/dav1d/headers.rs
> +        unsafe { *<*const _>::from(self).cast::<u8>() }
We shouldn't use unsafe here.  You can just do `as u8` since the enum is data-less (only the variants).

2024-03-21 19:01 UTC, kkysen reviewed
@fbossen, could I push a change?  I think it's easier to show that way than explaining it in scattered comments.  I want to add an `enum SgrIdx` to simplify this.

2024-03-21 19:04 UTC, fbossen commented
> @fbossen, could I push a change? I think it's easier to show that way than explaining it in scattered comments. I want to add an `enum SgrIdx` to simplify this.

No problem. Please do.

2024-03-21 23:00 UTC, fbossen commented
> @fbossen, how does [f72d0b9](https://github.com/memorysafety/rav1d/commit/f72d0b902c4189202901f85f2fe47a4be1a04c2b) look?

LGTM

2024-03-22 02:07 UTC, kkysen approved these changes

2024-03-22 02:07 UTC, merged