`struct Rav1dFrameContext_lf`: Add inner mutability
memorysafety/rav1d pull request #946
Opened 2024-04-02 21:19 UTC by rinon

Adds inner mutability to the `cdef_line_buf`, and `lr_line_buf` fields by using locks taken without blocking. Any blocking indicates contention that we should address in other ways.

2024-04-05 01:26 UTC, kkysen reviewed
If there is no contention, why are the `.try_*()` methods not used everywhere?

2024-04-12 06:53 UTC, rinon commented
> If there is no contention, why are the `.try_*()` methods not used everywhere?

Good point, I just checked and I'm going to switch this to disjoint mut, there is concurrent access.

2024-04-20 00:50 UTC, rinon commented
This has changed significantly and could use a fresh look from one of you.

2024-04-20 14:22 UTC, kkysen requested changes
I think `cdef_line_buf` is over-aligned now.  Other than that, everything looks generally good, but a bunch of the index calculations were confusing, and I think they can be simplified a lot (closer to what C was doing), so I made some suggestions there.

2024-04-20 14:22 UTC, kkysen commented on src/lf_apply.rs
>              };
```suggestion
            let px_stride = BD::pxstride(dst_stride);
            let px_abs_stride = px_stride.unsigned_abs();
            // Copy the top part of the stored loop filtered pixels from the
            // previous sb row needed above the first stripe of this sb row.
            let dst_idx = dst_offset - if dst_stride < 0 { 3 * px_abs_stride } else { 0 };
            let src_idx = (dst_idx as isize + top * px_stride) as usize;
```

2024-04-20 14:22 UTC, kkysen commented on src/lf_apply.rs
> +                    };
```suggestion
                    let src_idx = (dst_offset as isize - BD::pxstride(dst_stride)) as usize;
                    let dst_idx = dst_offset;
```

2024-04-20 14:22 UTC, kkysen commented on src/lf_apply.rs
>                  let dst_abs_px_stride = BD::pxstride(dst_stride.unsigned_abs());
```suggestion
```

2024-04-20 15:40 UTC, rinon commented on src/internal.rs
> +    pub cdef_line_buf: DisjointMut<AlignedVec64<u8>>, /* AlignedVec32<DynPixel> */
I needed the two buffers to be the same type so we can pass either to backup_lpf

2024-04-20 15:41 UTC, rinon commented on src/cdef_apply.rs
> +    dst_buf: &DisjointMut<AlignedVec64<u8>>,
Why would that help? I don't understand what "things like this" are here.

2024-04-20 15:43 UTC, rinon commented
I don't want to simplify the indexing in this PR. I considered it but that should be a simpler follow up and doesn't need to happen now.

2024-04-20 15:49 UTC, kkysen commented on src/cdef_apply.rs
> +    dst_buf: &DisjointMut<AlignedVec64<u8>>,
Things like which `u8`s are meant to be pixels, which are meant to be coefs, etc.  We do that here with a comment on the function; it'd be better if we just put it in the type, which is trivial to do (though not necessary to do in this PR).

2024-04-20 15:50 UTC, kkysen commented on src/internal.rs
> +    pub cdef_line_buf: DisjointMut<AlignedVec64<u8>>, /* AlignedVec32<DynPixel> */
Ahh.  Hmm.  I guess over-alignment isn't that bad.  Could you leave a comment here saying that was why and it really needs to be 32?

2024-04-20 15:51 UTC, rinon commented on src/cdef_apply.rs
> +    dst_buf: &DisjointMut<AlignedVec64<u8>>,
Ahhh so

```rust
type DynPixel = u8;
```

2024-04-20 15:52 UTC, kkysen commented on src/cdef_apply.rs
> +    dst_buf: &DisjointMut<AlignedVec64<u8>>,
Yeah pretty much.

2024-04-22 19:25 UTC, rinon commented on src/cdef_apply.rs
> +    dst_buf: &DisjointMut<AlignedVec64<u8>>,
Let's do that in a separate change, it will be noisy.

2024-04-22 19:41 UTC, merged

2024-04-23 00:10 UTC, kkysen commented on src/cdef_apply.rs
> +    dst_buf: &DisjointMut<AlignedVec64<u8>>,
Yeah, agree, that's what I was suggesting.