`struct TxLpfRightEdge`: Add inner mutability
memorysafety/rav1d pull request #947
Opened 2024-04-02 21:19 UTC by rinon

Adds inner mutability to the right edge split vector by using DisjointMut and narrower ranges for reading and writing data.

2024-04-02 23:51 UTC, randomPoison approved these changes

2024-04-05 01:47 UTC, kkysen requested changes

2024-04-05 01:47 UTC, kkysen commented on src/internal.rs
> +    pub fn copy_from_slice_y(&self, index: Range<usize>, src: &[u8]) {
Don't all of these methods, `fn copy_from_slice_{y,uv}` and `fn get`, need to be `unsafe`?  Their safeness relies on the specific `index`es passed.  It's clear that `y` and `uv` are non-overlapping (statically known), but within `y` and `uv`, the `index`es could overlap, so these all need to be `unsafe`, right?

2024-04-05 01:47 UTC, kkysen commented on src/internal.rs
> +        }
The `fn new` here was specifically a `const fn new`, so if we're not gonna make it `const`, there's no point in having it, as we already `#[derive(Default)]`.

2024-04-08 23:00 UTC, merged